window.KOMA=window.KOMA||{};
(function(K){
if(K._aiEvFixPatched)return;
K._aiEvFixPatched=true;
const EV_VERSION='20260713-ev-3';
function arr(x){return Array.isArray(x)?x:[];}
function mini(p){return p?{id:p.id,name:p.n,fig:p.fig,pos:p.pos||null,owner:p.owner,mp:p.mp,wait:p.wait||0,cond:p.status&&p.status.condition||null,mpMinus:p.status&&p.status.mpMinus||0,boss:!!p.boss}:null;}
function dist(a,b){if(!a||!b)return 99;if(a===b)return 0;const seen=new Map([[a,0]]),q=[a];while(q.length){const c=q.shift(),d=seen.get(c);for(const n of K.neigh(c)){if(seen.has(n))continue;if(n===b)return d+1;seen.set(n,d+1);q.push(n);}}return 99;}
function wheel(p){try{const w=K.wheelFor?K.wheelFor(p,true):[];const t=w.reduce((a,b)=>a+(b.s||1),0)||1;return w.map(x=>({seg:x,p:(x.s||1)/t}));}catch(e){return[];}}
function statusValue(e){if(!e)return 0;let v=0;if(e.condition==='sleep'||e.condition==='frozen')v+=340;if(e.condition==='paralyze')v+=230;if(e.condition==='confuse')v+=170;if(e.condition==='toxic')v+=230;if(e.condition==='poison'||e.condition==='burn')v+=120;if(e.wait)v+=190*e.wait;if(e.mpMinus)v+=120*e.mpMinus;if(e.swap)v+=130;if(e.bench)v+=260;if(e.pushLine)v+=150;if(e.selfWait)v-=80*e.selfWait;if(e.selfko)v-=500;return v;}
function unitValue(p){if(!p)return 0;let v=p.boss?1250:760;v+=(p.mp||0)*85;if(p.pos){const own=dist(p.pos,K.TARGET[p.owner]);const enemy=dist(p.pos,K.TARGET[K.other(p.owner)]);v+=Math.max(0,6-own)*80;if(p.pos===K.TARGET[K.other(p.owner)])v+=650;if(p.pos===K.TARGET[p.owner])v+=260;if(enemy<=1)v+=120;}if(p.status){if(p.status.condition==='sleep'||p.status.condition==='frozen')v-=310;if(p.status.condition==='paralyze')v-=190;if(p.status.condition==='confuse')v-=130;if(p.status.condition==='poison'||p.status.condition==='toxic'||p.status.condition==='burn')v-=100;if(p.status.mpMinus)v-=120*p.status.mpMinus;}if(p.wait)v-=170*p.wait;return v;}
function canGoal(owner){if(!K.s||!K.s[owner])return false;for(const p of arr(K.s[owner].field))if(K.canAct(p)&&K.moveTargets(p,owner).includes(K.TARGET[owner])&&!K.at(K.TARGET[owner]))return true;for(const p of arr(K.s[owner].bench))if(K.entryTargets(p,owner).includes(K.TARGET[owner])&&!K.at(K.TARGET[owner]))return true;return false;}
function surroundRiskPiece(p,node=p&&p.pos){if(!p||!node)return 0;const enemy=K.other(p.owner),ns=K.neigh(node);if(!ns.length)return 0;let enemyN=0,empty=0;for(const n of ns){const o=K.at(n);if(o&&o.owner===enemy)enemyN++;else if(!o)empty++;}if(enemyN===ns.length)return 1;if(enemyN>=2&&empty<=1)return .75;if(enemyN>=2)return .42;if(enemyN>=1&&empty===0)return .28;return 0;}
function surroundGainAt(owner,node){const enemy=K.other(owner);let gain=0;for(const e of arr(K.s&&K.s[enemy]&&K.s[enemy].field)){const ns=K.neigh(e.pos);if(ns.length&&ns.every(n=>{if(n===node)return true;const o=K.at(n);return o&&o.owner===owner;}))gain+=unitValue(e);}return gain;}
function boardScore(owner){if(!K.s)return 0;const enemy=K.other(owner);let v=0;v+=(arr(K.s[enemy].pc).length-arr(K.s[owner].pc).length)*900;v+=(arr(K.s[owner].field).length-arr(K.s[enemy].field).length)*260;for(const p of arr(K.s[owner].field)){v+=unitValue(p);v-=surroundRiskPiece(p)*unitValue(p)*.9;v+=surroundGainAt(owner,p.pos)*.35;}for(const p of arr(K.s[enemy].field)){v-=unitValue(p);v+=surroundRiskPiece(p)*unitValue(p)*.65;v-=surroundGainAt(enemy,p.pos)*.25;}if(canGoal(owner))v+=140000;if(canGoal(enemy))v-=180000;const block=K.at(K.TARGET[enemy]);if(block&&block.owner===owner)v+=90000;const blocked=K.at(K.TARGET[owner]);if(blocked&&blocked.owner===enemy)v-=95000;return v;}
function withPlan(plan,fn){if(!plan)return fn();if(plan.type==='move'){const old=plan.p.pos;plan.p.pos=plan.n;try{return fn();}finally{plan.p.pos=old;}}if(plan.type==='deploy'){const pl=K.s[plan.p.owner],old=plan.p.pos;pl.bench=pl.bench.filter(x=>x.id!==plan.p.id);pl.field.push(plan.p);plan.p.pos=plan.n;try{return fn();}finally{pl.field=pl.field.filter(x=>x.id!==plan.p.id);pl.bench.push(plan.p);plan.p.pos=old;}}return fn();}
function genPlans(owner){const out=[];if(!K.s||!K.s[owner])return out;for(const p of arr(K.s[owner].field)){if(K.canWakeByAlly&&K.canWakeByAlly(p))out.push({type:'wake',p});if(!K.canAct(p))continue;for(const e of K.battleableEnemies(p))out.push({type:'battle',p,d:e});for(const n of K.moveTargets(p,owner))if(!K.at(n))out.push({type:'move',p,n});}for(const p of arr(K.s[owner].bench))for(const n of K.entryTargets(p,owner))if(!K.at(n))out.push({type:'deploy',p,n});return out;}
function battleStats(a,d){const aw=wheel(a),dw=wheel(d);let atkWin=0,defWin=0,draw=0,atkKo=0,defKo=0,atkStatus=0,defStatus=0,atkDamage=0,defDamage=0;for(const A of aw)for(const D of dw){const p=A.p*D.p;let o=null;try{o=K.compare?K.compare(A.seg,D.seg,a,d):null;}catch(e){}if(!o){const ad=A.seg.d||0,dd=D.seg.d||0;o={winner:ad>dd?'atk':dd>ad?'def':'draw',ko:Math.max(ad,dd)>=100};}
    if(o.blue||o.winner==='draw'){draw+=p;}else if(o.winner==='atk'){atkWin+=p;if(o.ko)defKo+=p;}else if(o.winner==='def'){defWin+=p;if(o.ko)atkKo+=p;}
    atkStatus+=p*statusValue(A.seg.e);defStatus+=p*statusValue(D.seg.e);atkDamage+=p*(A.seg.d||0);defDamage+=p*(D.seg.d||0);
  }
  const expected=(atkWin-defWin)*520+defKo*unitValue(d)-atkKo*unitValue(a)+atkStatus*.85-defStatus*.95+(atkDamage-defDamage)*1.4;
  return {atkWin:+atkWin.toFixed(3),defWin:+defWin.toFixed(3),draw:+draw.toFixed(3),atkKo:+atkKo.toFixed(3),defKo:+defKo.toFixed(3),atkStatus:Math.round(atkStatus),defStatus:Math.round(defStatus),atkDamage:Math.round(atkDamage),defDamage:Math.round(defDamage),expected:Math.round(expected)};
}
function planRisk(plan,owner){if(!plan)return 0;const enemy=K.other(owner);let r=0;if(plan.type==='move'||plan.type==='deploy'){if(plan.n===K.TARGET[owner])return -999999;if(surroundRiskPiece(plan.p,plan.n)>=.75)r+=unitValue(plan.p)*.9;if(plan.n===K.TARGET[enemy])r-=70000;withPlan(plan,()=>{if(canGoal(enemy))r+=160000;});}
  if(plan.type==='battle'&&plan.d){const b=battleStats(plan.p,plan.d);r+=b.atkKo*unitValue(plan.p);if(plan.p.pos===K.TARGET[enemy])r+=120000;if(plan.d.pos===K.TARGET[owner])r-=85000;if(K.moveTargets(plan.d,enemy).includes(K.TARGET[enemy]))r-=60000;}
  return r;
}
function opponentReply(owner){const enemy=K.other(owner);let best=null;for(const p of genPlans(enemy)){const ev=scorePlan(p,enemy,true);if(!best||ev.score>best.score)best=ev;}return best;}
function reason(plan,owner,delta,battle,risk,reply){const r=[];if(plan.type==='move'||plan.type==='deploy'){if(plan.n===K.TARGET[owner])r.push('immediate_goal');if(plan.n===K.TARGET[K.other(owner)])r.push('block_enemy_goal');if(delta>0)r.push('board_gain');if(risk>50000)r.push('self_risk');}
 if(plan.type==='battle'){if(battle.defKo>.12)r.push('can_pc_enemy');if(battle.atkKo>.12)r.push('may_die');if(battle.expected>0)r.push('battle_plus_ev');else r.push('battle_minus_ev');}
 if(reply&&reply.score>90000)r.push('opponent_reply_danger');return r;}
function scorePlan(plan,owner,shallow){const before=boardScore(owner);let after=before,battle=null;if(plan.type==='move'||plan.type==='deploy'||plan.type==='wake')after=withPlan(plan,()=>boardScore(owner));let tactical=0;if(plan.type==='battle'&&plan.d){battle=battleStats(plan.p,plan.d);tactical+=battle.expected;if(plan.d.pos===K.TARGET[owner])tactical+=85000;if(K.moveTargets(plan.d,K.other(owner)).includes(K.TARGET[K.other(owner)]))tactical+=55000;}if((plan.type==='move'||plan.type==='deploy')&&plan.n===K.TARGET[owner])tactical+=1000000;if((plan.type==='move'||plan.type==='deploy')&&plan.n===K.TARGET[K.other(owner)])tactical+=110000;const delta=after-before;const risk=planRisk(plan,owner);let reply=null,replyTax=0;if(!shallow){reply=withPlan(plan,()=>opponentReply(owner));if(reply)replyTax=Math.max(0,reply.score)*.48;}const score=delta+tactical-risk-replyTax;return {plan,score,delta:Math.round(delta),tactical:Math.round(tactical),risk:Math.round(risk),reply:reply&&summary(reply),battle,reasons:reason(plan,owner,delta,battle||{},risk,reply)};}
function summary(ev){return ev?{type:ev.plan.type,piece:mini(ev.plan.p),to:ev.plan.n||null,defender:mini(ev.plan.d),score:Math.round(ev.score),delta:ev.delta,tactical:ev.tactical,risk:ev.risk,reasons:ev.reasons,battle:ev.battle}:null;}
function bestEv(owner){const ranked=genPlans(owner).map(p=>scorePlan(p,owner,false)).sort((a,b)=>b.score-a.score);return {best:ranked[0]||null,top:ranked.slice(0,5).map(summary)};}
function immediate(plan,owner){return plan&&(plan.type==='move'||plan.type==='deploy')&&plan.n===K.TARGET[owner];}
function protectedPlan(plan){return !!(plan&&(plan.score>=800000||String(plan.why||'').indexOf('emergency_')===0||String(plan.why||'').indexOf('guard_')===0));}
function chosenSummary(plan,note){return plan?{type:plan.type,piece:mini(plan.p),to:plan.n||null,defender:mini(plan.d),score:Math.round(plan.score||0),why:plan.why||note||null}:null;}
const choose0=K.chooseAiPlan;
if(choose0){K.chooseAiPlan=function(){const base=choose0.apply(this,arguments);const baseEv=base?scorePlan(base,'p2',false):null;if(immediate(base,'p2')){if(K.learningAddEvent)K.learningAddEvent('ai_ev_choice',{version:EV_VERSION,base:summary(baseEv),evBest:summary(baseEv),top:baseEv?[summary(baseEv)]:[],chosen:chosenSummary(base,'immediate_goal'),used:false,note:'immediate_goal_kept'});return base;}if(protectedPlan(base)){if(K.learningAddEvent)K.learningAddEvent('ai_ev_choice',{version:EV_VERSION,base:summary(baseEv),evBest:summary(baseEv),top:baseEv?[summary(baseEv)]:[],chosen:chosenSummary(base,'protected_defense'),used:false,note:'protected_defense_kept'});return base;}const ev=bestEv('p2');let chosen=base;if(ev.best&&(!baseEv||ev.best.score>baseEv.score+75000)){chosen={...ev.best.plan,score:ev.best.score,why:'ev_board_expected_value'};}
  if(K.learningAddEvent)K.learningAddEvent('ai_ev_choice',{version:EV_VERSION,base:summary(baseEv),evBest:summary(ev.best),top:ev.top,chosen:chosenSummary(chosen),used:chosen!==base,note:chosen!==base?'changed_by_expected_value':'kept_base'});
  if(chosen!==base&&K.log)K.log('AI期待値: 勝率/死亡リスク/盤面損得/相手の返しを見て手を変更します。');return chosen;};}
})(window.KOMA);
