window.KOMA=window.KOMA||{};
(function(K){
K.aiTraining={decisions:[],games:0,lastLearned:null};
function keys(){return Object.keys(K.DEFAULT_AI_WEIGHTS||{});}
function save(w){return K.saveAiWeights?K.saveAiWeights(w):w;}
function get(){return K.getAiWeights?K.getAiWeights():JSON.parse(JSON.stringify(K.DEFAULT_AI_WEIGHTS||{}));}
K.recordAiDecision=function(feat,score){if(!K.aiTraining)K.aiTraining={decisions:[],games:0};K.aiTraining.decisions.push({feat:feat||{},score:score||0});if(K.aiTraining.decisions.length>120)K.aiTraining.decisions.shift();};
K.learnFromOutcome=function(winner){if(!K.aiTraining||!K.aiTraining.decisions.length)return;const reward=winner==='p2'?1:winner==='p1'?-1:0;if(!reward)return;const W=get(),base=K.DEFAULT_AI_WEIGHTS,start=Math.max(0,K.aiTraining.decisions.length-8);for(let i=start;i<K.aiTraining.decisions.length;i++){const d=K.aiTraining.decisions[i],rec=(i-start+1)/8,lr=winner==='p1'?.075:.04;for(const k of keys()){const x=Number(d.feat[k]||0);if(!x)continue;W[k]+=reward*x*Math.max(1,Math.abs(base[k]||1))*lr*rec;}}save(W);K.aiTraining.games=(K.aiTraining.games||0)+1;K.aiTraining.decisions=[];K.log('AI反省学習: '+winner+' を反映。直近手を重点更新 / 対局 '+K.aiTraining.games);};
function sampleFeature(){const r=Math.random,feat={};for(const k of keys())feat[k]=0;const mode=Math.floor(r()*7);feat.tempo=1;if(mode===0)feat.goalNow=1;if(mode===1){feat.blockGoal=1;feat.oppGoal=1;}if(mode===2){feat.battle=r()*2-0.4;feat.statusInflict=r();feat.statusSuffer=r()*.7;}if(mode===3){feat.surroundKill=r();feat.surroundRisk=r()*1.6;}if(mode===4){feat.goalDist=r();feat.goalThreat=r()>.55?1:0;feat.cornerThreat=r()>.82?1:0;}if(mode===5){feat.spawnBlock=r()>.4?1:0;feat.ownSpawnBlocked=r()>.55?1:0;}if(mode===6){feat.center=r();feat.field=r()*2-1;feat.pc=r()*2-1;}return feat;}
function expert(feat){let s=0;if(feat.goalNow)s+=100;if(feat.blockGoal&&feat.oppGoal)s+=95;if(feat.oppGoal&&!feat.blockGoal)s-=100;s+=feat.goalDist*15+feat.goalThreat*35+feat.cornerThreat*45;s+=feat.spawnBlock*22-feat.ownSpawnBlocked*35;s+=feat.surroundKill*45-feat.surroundRisk*38;s+=feat.battle*18+feat.statusInflict*10-feat.statusSuffer*12;s+=feat.center*8+feat.pc*8+feat.field*4;return s;}
function predict(feat,W){let s=0;for(const k of keys())s+=(W[k]||0)*(feat[k]||0)/Math.max(1,Math.abs((K.DEFAULT_AI_WEIGHTS||{})[k]||1));return s;}
K.runLocalTraining=function(rounds){rounds=rounds||900;const W=get(),base=K.DEFAULT_AI_WEIGHTS,rate=.1;let err=0;for(let i=0;i<rounds;i++){const feat=sampleFeature(),y=expert(feat),p=predict(feat,W),e=y-p;err+=Math.abs(e);for(const k of keys()){const x=feat[k]||0;if(!x)continue;W[k]+=e*x*rate*Math.max(1,Math.abs(base[k]||1))/100;}}const m=K.playMemory&&K.playMemory();if(m&&m.n){for(const k of keys()){const avg=(m.f&&m.f[k]||0)/m.n;if(avg)W[k]-=avg*Math.max(1,Math.abs(base[k]||1))*.012;}}save(W);const avg=Math.round(err/rounds);K.log('AI簡易学習: '+rounds+' サンプル完了 / 平均誤差 '+avg+' / 重み保存済み');K.render&&K.render();};
K.resetLocalTraining=function(){K.resetAiWeights&&K.resetAiWeights();if(K.aiTraining)K.aiTraining.decisions=[];try{localStorage.removeItem('koma_ai_play_memory_v1');}catch(e){}K.log('AI学習重みと手筋記憶を初期化しました。');K.render&&K.render();};
function dist(a,b){if(a===b)return 0;const q=[a],seen=new Map([[a,0]]);while(q.length){const c=q.shift(),d=seen.get(c);for(const n of K.neigh(c)){if(seen.has(n))continue;if(n===b)return d+1;seen.set(n,d+1);q.push(n);}}return 99;}
function other(o){return o==='p1'?'p2':'p1';}
function plans(o){const r=[];for(const p of K.s[o].field){if(K.canWakeByAlly(p))r.push({type:'wake',p});if(!K.canAct(p))continue;for(const e of K.battleableEnemies(p))r.push({type:'battle',p,d:e});for(const n of K.moveTargets(p,o))r.push({type:'move',p,n});}for(const p of K.s[o].bench)for(const n of K.entryTargets(p,o))r.push({type:'deploy',p,n});return r;}
function goals(o){const r=[];for(const p of K.s[o].field)if(K.canAct(p)&&K.moveTargets(p,o).includes(K.TARGET[o]))r.push(p);for(const p of K.s[o].bench)if(K.entryTargets(p,o).includes(K.TARGET[o]))r.push(p);return r;}
function mem(){try{return JSON.parse(localStorage.getItem('koma_ai_play_memory_v1')||'{"n":0,"f":{}}');}catch(e){return{n:0,f:{}};}}
function savem(m){try{localStorage.setItem('koma_ai_play_memory_v1',JSON.stringify(m));}catch(e){}}
K.playMemory=mem;
function risk(p,n){const e=other(p.owner),old=p.pos;p.pos=n;const ns=K.neigh(n);let en=0,emp=0;for(const x of ns){const a=K.at(x);if(a&&a.owner===e)en++;else if(!a)emp++;}p.pos=old;if(ns.length&&en===ns.length)return 5;if(en>=2&&emp<=1)return 3;if(en>=2)return 1;return 0;}
function gain(p,n){const e=other(p.owner),old=p.pos;p.pos=n;let g=0;for(const x of K.s[e].field){const ns=K.neigh(x.pos);if(ns.length&&ns.every(m=>{const a=K.at(m);return a&&a.owner===p.owner;}))g++;}p.pos=old;return g;}
function feat(p,o){const e=other(o),f={goalNow:0,blockGoal:0,oppGoal:0,goalDist:0,goalThreat:0,spawnBlock:0,ownSpawnBlocked:0,center:0,surroundKill:0,surroundRisk:0,battle:0,tempo:1};if(!p)return f;if((p.type==='move'||p.type==='deploy')&&p.n===K.TARGET[o])f.goalNow=1;if(goals(e).length)f.oppGoal=1;if(p.type==='battle'){f.battle=(K.battleScore?K.battleScore(p.p,p.d):0)/200;if(K.moveTargets(p.d,e).includes(K.TARGET[e]))f.blockGoal=1;return f;}if(p.type==='move'||p.type==='deploy'){const n=p.n,d=dist(n,K.TARGET[o]);f.goalDist=Math.max(0,6-d)/6;if(K.effectiveMp(p.p,o)>=d)f.goalThreat=1;if(n===K.TARGET[e])f.blockGoal=1;if(K.SPAWN[e].includes(n))f.spawnBlock=1;if(K.SPAWN[o].includes(n))f.ownSpawnBlocked=1;if(['it1','it2','it3','im1','im3','ib1','ib2','ib3'].includes(n))f.center=1;f.surroundKill=gain(p.p,n);f.surroundRisk=risk(p.p,n);for(const a of K.s[e].field)if(a.pos&&K.neigh(n).includes(a.pos))f.battle+=(K.battleScore?K.battleScore(p.p,a):0)/240;}return f;}
function value(f){const W=get();let s=0;for(const k in f)s+=(W[k]||0)*(f[k]||0);return s;}
function like(f){const m=mem();if(!m.n)return 0;let s=0;for(const k in f)s+=(m.f[k]||0)/m.n*(f[k]||0);return s*900;}
function score(p,o){const e=other(o),f=feat(p,o);let s=value(f)*.18;if(f.goalNow)s+=1000000;if(f.blockGoal&&goals(e).length)s+=900000;if(goals(e).length&&!f.blockGoal)s-=900000;if(p.type==='battle')s+=(K.battleScore?K.battleScore(p.p,p.d):0)*12;return s;}
function withPlan(p,fn){if(p.type==='move'){const old=p.p.pos;p.p.pos=p.n;const r=fn();p.p.pos=old;return r;}if(p.type==='deploy'){const pl=K.s[p.p.owner],old=p.p.pos;pl.bench=pl.bench.filter(x=>x.id!==p.p.id);pl.field.push(p.p);p.p.pos=p.n;const r=fn();pl.field=pl.field.filter(x=>x.id!==p.p.id);pl.bench.push(p.p);p.p.pos=old;return r;}return fn();}
function reply(p){return withPlan(p,()=>{let b=0;for(const q of plans('p1'))b=Math.max(b,score(q,'p1')+like(feat(q,'p1')));return b;});}
K.chooseAiPlan=function(){const ps=plans('p2'),win=ps.find(p=>(p.type==='move'||p.type==='deploy')&&p.n===K.TARGET.p2);if(win)return{...win,score:1000000,feat:feat(win,'p2')};let best=null;for(const p of ps){const f=feat(p,'p2');let sc=score(p,'p2')-reply(p)*.75+Math.random();if(!best||sc>best.score)best={...p,score:sc,feat:f};}return best;};
function record(p){if(!p||!p.p||p.p.owner!=='p1')return;const m=mem(),f=feat(p,'p1');m.n=(m.n||0)+1;for(const k in f)m.f[k]=(m.f[k]||0)+f[k];savem(m);}
const oldMove=K.movePiece,oldDeploy=K.deploy,oldBattle=K.startBattle;
K.movePiece=function(p,n){if(K.s&&K.s.turn==='p1')record({type:'move',p,n});return oldMove.apply(this,arguments);};
K.deploy=function(p,n){if(K.s&&K.s.turn==='p1')record({type:'deploy',p,n});return oldDeploy.apply(this,arguments);};
K.startBattle=function(id){const a=K.byId(K.s.pendingAttacker||K.s.selectedId),d=K.byId(id);if(a&&a.owner==='p1'&&d)record({type:'battle',p:a,d});return oldBattle.apply(this,arguments);};
const oldRenderSetter=function(){if(!K.render||K.render._learnHook)return;const baseRender=K.render;K.render=function(){baseRender();if(K.s&&K.s.win&&!K.s._learned){K.s._learned=true;K.learnFromOutcome&&K.learnFromOutcome(K.s.win);}};K.render._learnHook=true;};
const oldBind=K.bindUi;
K.bindUi=function(){oldBind&&oldBind();const train=document.querySelector('#trainAiBtn'),reset=document.querySelector('#resetLearnBtn');if(train)train.onclick=function(){K.runLocalTraining(1200);};if(reset)reset.onclick=function(){K.resetLocalTraining();};oldRenderSetter();};
})(window.KOMA);
