window.KOMA=window.KOMA||{};
(function(K){
const W={goalNow:1000000,blockGoal:900000,oppGoal:-950000,pc:520,field:105,goalDist:32,goalThreat:5200,cornerThreat:18000,spawnBlock:1250,ownSpawnBlocked:-1450,center:170,surroundKill:8500,surroundRisk:-5600,battle:13,statusInflict:4,statusSuffer:-5,tempo:90};
function arr(x){return Array.isArray(x)?x:[];}
function dist(a,b){if(a===b)return 0;const seen=new Map([[a,0]]),q=[a];while(q.length){const c=q.shift(),d=seen.get(c);for(const n of K.neigh(c)){if(seen.has(n))continue;if(n===b)return d+1;seen.set(n,d+1);q.push(n);}}return 99;}
function segProb(p){const w=K.wheelFor(p,true),t=w.reduce((a,b)=>a+b.s,0)||1;return w.map(x=>({seg:K.cloneSeg(x),p:x.s/t}));}
function statusValue(seg){const e=seg.e;if(!e)return 0;let v=0;if(e.condition==='sleep')v+=300;if(e.condition==='frozen')v+=280;if(e.condition==='paralyze')v+=230;if(e.condition==='confuse')v+=180;if(e.condition==='toxic')v+=210;if(e.condition==='poison')v+=115;if(e.wait)v+=165*e.wait;if(e.mpMinus)v+=95*e.mpMinus;if(e.bench)v+=220;if(e.swap)v+=90;if(e.selfko)v+=140;return v;}
function pieceStatusValue(p){let v=0;if(p.wait>0)v-=150*p.wait;if(p.status.mpMinus)v-=95*p.status.mpMinus;if(p.status.condition==='sleep')v-=320;if(p.status.condition==='frozen')v-=300;if(p.status.condition==='paralyze')v-=210;if(p.status.condition==='confuse')v-=150;if(p.status.condition==='toxic')v-=220;if(p.status.condition==='poison')v-=120;if(p.status.condition==='burn')v-=120;return v;}
function whiteBias(p){const w=K.wheelFor(p,true),t=w.reduce((a,b)=>a+b.s,0)||1;let dmg=0,st=0;for(const seg of w){if(seg.c==='white'||seg.c==='gold')dmg+=seg.s;if(statusValue(seg)>0)st+=seg.s;}return Math.max(0,dmg-st*.35)/t;}
function statusThreat(p){let v=0;for(const x of segProb(p))v+=x.p*statusValue(x.seg);return v;}
K.battleScore=function(a,d){let score=0;for(const A of segProb(a))for(const D of segProb(d)){const o=K.compare(A.seg,D.seg,a,d),p=A.p*D.p;if(o.blue)score+=0;else if(o.winner==='atk')score+=p*(o.ko?190:52+statusValue(A.seg));else if(o.winner==='def')score-=p*(o.ko?205:52+statusValue(D.seg));else if(o.mode==='damage-draw')score+=p*(statusValue(A.seg)-statusValue(D.seg))*.55;}score+=statusThreat(a)*whiteBias(d)*.7;score-=statusThreat(d)*whiteBias(a)*.9;return score;};
function goalThreats(owner){const out=[];for(const p of K.s[owner].field)if(K.canAct(p)&&K.moveTargets(p,owner).includes(K.TARGET[owner]))out.push(p);for(const p of K.s[owner].bench)if(K.entryTargets(p,owner).includes(K.TARGET[owner]))out.push(p);return out;}
function genPlans(owner){const plans=[];for(const p of K.s[owner].field){if(K.canWakeByAlly(p))plans.push({type:'wake',p});if(!K.canAct(p))continue;for(const e of K.battleableEnemies(p))plans.push({type:'battle',p,d:e});for(const n of K.moveTargets(p,owner))plans.push({type:'move',p,n});}
for(const p of K.s[owner].bench)for(const n of K.entryTargets(p,owner))plans.push({type:'deploy',p,n});return plans;}
function withPlan(plan,fn){if(plan.type==='move'){const old=plan.p.pos;plan.p.pos=plan.n;const r=fn();plan.p.pos=old;return r;}if(plan.type==='deploy'){const pl=K.s[plan.p.owner],oldPos=plan.p.pos;pl.bench=pl.bench.filter(x=>x.id!==plan.p.id);pl.field.push(plan.p);plan.p.pos=plan.n;const r=fn();pl.field=pl.field.filter(x=>x.id!==plan.p.id);pl.bench.push(plan.p);plan.p.pos=oldPos;return r;}if(plan.type==='battle'){return fn();}return fn();}
function surroundRisk(p,node){const enemy=K.other(p.owner),old=p.pos;p.pos=node;const ns=K.neigh(node);let enemyN=0,empty=0;for(const n of ns){const o=K.at(n);if(o&&o.owner===enemy)enemyN++;else if(!o)empty++;}p.pos=old;if(ns.length&&enemyN===ns.length)return 99999;if(enemyN>=2&&empty<=1)return 4200;if(enemyN>=2)return 1500;if(enemyN>=1&&empty===0)return 900;return 0;}
function surroundGain(p,node){const enemy=K.other(p.owner),old=p.pos;p.pos=node;let gain=0;for(const e of K.s[enemy].field){const ns=K.neigh(e.pos);if(ns.length&&ns.every(n=>{const o=K.at(n);return o&&o.owner===p.owner;}))gain+=1;}p.pos=old;return gain;}
function immediateWin(owner){return goalThreats(owner).length>0;}
function mpCornerThreat(p,owner,node=p.pos){return p&&K.canAct(p)&&K.effectiveMp(p,owner)>=3&&K.CORNERS[owner].includes(node)&&K.effectiveMp(p,owner)>=dist(node,K.TARGET[owner]);}
function nodeValueForPiece(p,owner,node){const enemy=K.other(owner);let v=0;const d=dist(node,K.TARGET[owner]);v+=Math.max(0,120-d*W.goalDist);if(K.effectiveMp(p,owner)>=d)v+=W.goalThreat;if(mpCornerThreat(p,owner,node))v+=W.cornerThreat;if(node===K.TARGET[enemy])v+=W.blockGoal*.08;if(K.SPAWN[enemy].includes(node))v+=W.spawnBlock+K.s[enemy].bench.length*80;if(K.SPAWN[owner].includes(node))v+=W.ownSpawnBlocked;const centers=['it1','it2','it3','im1','im3','ib1','ib2','ib3'];if(centers.includes(node))v+=W.center;for(const e of K.s[enemy].field){if(e.pos&&K.neigh(node).includes(e.pos)){v+=K.battleScore(p,e)*W.battle;v+=statusThreat(p)*whiteBias(e)*W.statusInflict;v+=statusThreat(e)*whiteBias(p)*W.statusSuffer;}}
v+=surroundGain(p,node)*W.surroundKill;v+=surroundRisk(p,node)*W.surroundRisk/1000;return v;}
function boardEval(owner){const enemy=K.other(owner);let v=0;v+=(K.s[enemy].pc.length-K.s[owner].pc.length)*W.pc;v+=(K.s[owner].field.length-K.s[enemy].field.length)*W.field;for(const p of K.s[owner].field){v+=nodeValueForPiece(p,owner,p.pos);v+=pieceStatusValue(p);}for(const p of K.s[enemy].field){v-=nodeValueForPiece(p,enemy,p.pos);v-=pieceStatusValue(p);}if(immediateWin(owner))v+=W.goalNow*.35;if(immediateWin(enemy))v+=W.oppGoal*.35;return v;}
function planBaseScore(plan,owner){const enemy=K.other(owner);if((plan.type==='move'||plan.type==='deploy')&&plan.n===K.TARGET[owner])return W.goalNow;if(plan.type==='wake')return 2800+boardEval(owner);if(plan.type==='battle'){let sc=boardEval(owner)+520+K.battleScore(plan.p,plan.d)*16;if(K.moveTargets(plan.d,enemy).includes(K.TARGET[enemy]))sc+=55000;if(mpCornerThreat(plan.d,enemy))sc+=22000;return sc;}
return withPlan(plan,()=>{let sc=boardEval(owner);if(immediateWin(enemy)&&!immediateWin(owner))sc+=W.oppGoal;if(immediateWin(owner))sc+=120000;return sc;});}
function opponentBestScore(owner,limit=12){const enemy=K.other(owner);let best=-Infinity,plans=genPlans(enemy).map(p=>({p,score:planBaseScore(p,enemy)})).sort((a,b)=>b.score-a.score).slice(0,limit);for(const x of plans)best=Math.max(best,x.score);return best===-Infinity?0:best;}
function planScore(plan,owner){let base=planBaseScore(plan,owner);if(base>=W.goalNow)return base;return withPlan(plan,()=>{const enemy=K.other(owner);let sc=base;if(immediateWin(enemy)&&!immediateWin(owner))sc-=850000;const opp=opponentBestScore(owner);sc-=opp*.58;sc+=Math.random()*2;return sc;});}
function canOccupyGoal(owner,goal){let best=null;function set(plan,score){if(!best||score>best.score)best={...plan,score};}
for(const p of K.s[owner].field)if(K.canAct(p)&&K.moveTargets(p,owner).includes(goal))set({type:'move',p,n:goal},W.blockGoal);for(const p of K.s[owner].bench)if(K.entryTargets(p,owner).includes(goal))set({type:'deploy',p,n:goal},W.blockGoal-12000);return best;}
function defensivePlan(owner){const enemy=K.other(owner),th=goalThreats(enemy);if(!th.length)return null;let best=canOccupyGoal(owner,K.TARGET[enemy]);function set(plan,score){if(!best||score>best.score)best={...plan,score};}
for(const t of th.filter(x=>x.pos)){for(const p of K.s[owner].field){if(!K.canAct(p))continue;if(K.neigh(p.pos).includes(t.pos))set({type:'battle',p,d:t},W.blockGoal-25000+K.battleScore(p,t)*20);for(const n of K.moveTargets(p,owner))if(K.neigh(n).includes(t.pos))set({type:'move',p,n},W.blockGoal-65000+K.battleScore(p,t)*12-surroundRisk(p,n));}}
if(best)K.log('AI警戒: 次ターンのゴール負けを最優先で防ぎます。');return best;}
function canReachIfTargetEmpty(p,owner,target,guard){if(!p||!K.canAct(p))return false;const old=guard&&guard.pos;if(guard)guard.pos=null;try{return p.pos?K.moveTargets(p,owner).includes(target):K.entryTargets(p,owner).includes(target);}catch(e){return false;}finally{if(guard)guard.pos=old;}}
function threatsIfGuardVacated(owner,guard){const enemy=K.other(owner),target=K.TARGET[enemy],out=[];for(const p of arr(K.s&&K.s[enemy]&&K.s[enemy].field))if(canReachIfTargetEmpty(p,enemy,target,guard))out.push(p);for(const p of arr(K.s&&K.s[enemy]&&K.s[enemy].bench))if(canReachIfTargetEmpty(p,enemy,target,guard))out.push(p);return out;}
function defenderCanDislodge(d){if(!d)return true;try{for(const seg of K.wheelFor(d,true)){const e=seg.e||{};if(e.pushLine||e.swap||e.bench||e.selfko||e.selfBench||e.fly)return true;if((seg.c==='white'||seg.c==='gold')&&(seg.d||0)>0)return true;}}catch(e){return true;}return false;}
function guardDanger(plan,owner){if(!plan||!plan.p)return null;const enemy=K.other(owner),target=K.TARGET[enemy],guard=arr(K.s&&K.s[owner]&&K.s[owner].field).find(p=>p.pos===target);if(!guard||plan.p.id!==guard.id)return null;const threats=threatsIfGuardVacated(owner,guard);if(!threats.length)return null;if(plan.type==='move')return{target,guard,threats,reason:'leave_goal'};if(plan.type==='battle'&&defenderCanDislodge(plan.d))return{target,guard,threats,reason:'risky_guard_battle'};return null;}
function rankedPlans(owner){return genPlans(owner).map(p=>({p,score:planScore(p,owner)})).sort((a,b)=>b.score-a.score);}
function safeRankedPlan(owner,ranked){let blocked=null;for(const x of ranked){const gd=guardDanger(x.p,owner);if(gd){blocked=blocked||{...gd,plan:x.p,score:x.score};continue;}return{...x.p,score:x.score,blocked};}return blocked?{blocked,none:true}:null;}
function mini(p){return p?{id:p.id,name:p.n,fig:p.fig,pos:p.pos||null,owner:p.owner}:null;}
K.chooseAiPlan=function(){const win=genPlans('p2').find(p=>(p.type==='move'||p.type==='deploy')&&p.n===K.TARGET.p2);if(win)return{...win,score:W.goalNow};const def=defensivePlan('p2');if(def&&!guardDanger(def,'p2'))return def;const ranked=rankedPlans('p2');const safe=safeRankedPlan('p2',ranked);if(safe&&safe.none){const b=safe.blocked;K.log('AI警戒: '+b.guard.n+'は'+b.target+'を守ります。バトル/移動で空くと即ゴールされるため待機。');if(K.learningAddEvent)K.learningAddEvent('ai_guard_core_hold',{target:b.target,guard:mini(b.guard),threats:b.threats.map(mini),reason:b.reason,blockedPlan:{type:b.plan.type,piece:mini(b.plan.p),to:b.plan.n||null,defender:mini(b.plan.d),score:Math.round(b.score||0)}});return null;}if(safe&&safe.blocked&&K.learningAddEvent){const b=safe.blocked;K.learningAddEvent('ai_guard_core_skip',{target:b.target,guard:mini(b.guard),threats:b.threats.map(mini),reason:b.reason,blockedPlan:{type:b.plan.type,piece:mini(b.plan.p),to:b.plan.n||null,defender:mini(b.plan.d),score:Math.round(b.score||0)},chosen:{type:safe.type,piece:mini(safe.p),to:safe.n||null,defender:mini(safe.d),score:Math.round(safe.score||0)}});}return safe?{...safe}:null;};
K.runAi=function(){const s=K.s;if(!s.ai||s.turn!=='p2'||s.win||s.locked||s.phase!=='idle')return;const plan=K.chooseAiPlan();if(!plan){K.log('AIは動けません。');K.endTurn();return;}if(plan.type==='wake'){const old=plan.p.status.condition;plan.p.status.condition=null;K.log('AIは'+plan.p.n+'の'+(old==='frozen'?'こおり':'ねむり')+'を治しました。評価 '+Math.round(plan.score));K.endTurn();return;}if(plan.type==='deploy'){K.log('AI強化: '+plan.p.n+'を出撃。盤面評価 '+Math.round(plan.score));K.deploy(plan.p,plan.n);return;}if(plan.type==='move'){K.log('AI強化: '+plan.p.n+'が移動。盤面評価 '+Math.round(plan.score));K.movePiece(plan.p,plan.n);return;}if(plan.type==='battle'){K.s.pendingAttacker=plan.p.id;K.log('AI強化: '+plan.p.n+'で'+plan.d.n+'にバトル。盤面評価 '+Math.round(plan.score));K.startBattle(plan.d.id);}};
K.aiChooseEnemy=function(){const a=K.byId(K.s.pendingAttacker);if(!a||K.s.turn!=='p2'||K.s.phase!=='chooseBattle')return;let best=null;for(const e of K.battleableEnemies(a)){const sc=K.battleScore(a,e)*18+(K.moveTargets(e,'p1').includes(K.TARGET.p1)?60000:0)+(mpCornerThreat(e,'p1')?18000:0);if(!best||sc>best.sc)best={e,sc};}if(best&&best.sc>-120){K.log('AIは'+best.e.n+'にバトルします。');K.startBattle(best.e.id);}else{K.log('AIはバトルしないを選びました。');K.endTurn();}};
K.scheduleAi=function(){clearTimeout(K.aiTimer);if(K.s&&K.s.ai&&K.s.turn==='p2'&&!K.s.win&&!K.s.locked&&K.s.phase==='idle')K.aiTimer=setTimeout(K.runAi,520);};
})(window.KOMA);
