window.KOMA=window.KOMA||{};
(function(K){
function dist(a,b){if(a===b)return 0;const seen=new Map([[a,0]]),q=[a];while(q.length){const c=q.shift(),d=seen.get(c);for(const n of K.neigh(c)){if(seen.has(n))continue;if(n===b)return d+1;seen.set(n,d+1);q.push(n);}}return 99;}
function segProb(p){const w=K.wheelFor(p,true),t=w.reduce((a,b)=>a+b.s,0);return w.map(x=>({seg:K.cloneSeg(x),p:x.s/t}));}
function statusValue(seg){const e=seg.e;if(!e)return 0;let v=0;if(e.condition==='sleep')v+=260;if(e.condition==='paralyze')v+=210;if(e.condition==='confuse')v+=170;if(e.condition==='toxic')v+=190;if(e.condition==='poison')v+=100;if(e.condition==='frozen')v+=220;if(e.wait)v+=150*e.wait;if(e.mpMinus)v+=90*e.mpMinus;if(e.bench)v+=180;if(e.swap)v+=80;if(e.selfko)v+=120;return v;}
K.battleScore=function(a,d){let score=0;for(const A of segProb(a))for(const D of segProb(d)){const o=K.compare(A.seg,D.seg,a,d),p=A.p*D.p;if(o.blue)score+=0;else if(o.winner==='atk')score+=p*(o.ko?160:45+statusValue(A.seg));else if(o.winner==='def')score-=p*(o.ko?170:45+statusValue(D.seg));else if(o.mode==='damage-draw')score+=p*(statusValue(A.seg)-statusValue(D.seg))*.45;}return score;};
function goalThreats(owner){const out=[];for(const p of K.s[owner].field)if(K.canAct(p)&&K.moveTargets(p,owner).includes(K.TARGET[owner]))out.push(p);for(const p of K.s[owner].bench)if(K.entryTargets(p,owner).includes(K.TARGET[owner]))out.push(p);return out;}
function genPlans(owner){const plans=[];for(const p of K.s[owner].field){if(K.canWakeByAlly(p))plans.push({type:'wake',p});if(!K.canAct(p))continue;for(const e of K.battleableEnemies(p))plans.push({type:'battle',p,d:e});for(const n of K.moveTargets(p,owner))plans.push({type:'move',p,n});}
for(const p of K.s[owner].bench)for(const n of K.entryTargets(p,owner))plans.push({type:'deploy',p,n});return plans;}
function canOccupyGoal(owner,goal){for(const p of K.s[owner].field)if(K.canAct(p)&&K.moveTargets(p,owner).includes(goal))return{type:'move',p,n:goal,score:900000};for(const p of K.s[owner].bench)if(K.entryTargets(p,owner).includes(goal))return{type:'deploy',p,n:goal,score:890000};return null;}
function defensivePlan(owner){const enemy=K.other(owner),th=goalThreats(enemy);if(!th.length)return null;let best=canOccupyGoal(owner,K.TARGET[enemy]);function set(plan,score){if(!best||score>best.score)best={...plan,score};}
for(const t of th.filter(x=>x.pos)){for(const p of K.s[owner].field){if(!K.canAct(p))continue;if(K.neigh(p.pos).includes(t.pos))set({type:'battle',p,d:t},860000+K.battleScore(p,t));for(const n of K.moveTargets(p,owner))if(K.neigh(n).includes(t.pos))set({type:'move',p,n},810000+K.battleScore(p,t));}}
if(best)K.log('AI警戒: 次ターンのゴール負けを防ぎます。');return best;}
function surroundRisk(p,node){const enemy=K.other(p.owner),old=p.pos;p.pos=node;const ns=K.neigh(node);let enemyN=0,empty=0;for(const n of ns){const o=K.at(n);if(o&&o.owner===enemy)enemyN++;else if(!o)empty++;}p.pos=old;if(ns.length&&enemyN===ns.length)return 99999;if(enemyN>=2&&empty<=1)return 4200;if(enemyN>=2)return 1200;return 0;}
function planScore(plan,owner){const enemy=K.other(owner);if((plan.type==='move'||plan.type==='deploy')&&plan.n===K.TARGET[owner])return 999999;if(plan.type==='wake')return 2400;if(plan.type==='battle')return 500+K.battleScore(plan.p,plan.d)+ (K.moveTargets(plan.d,enemy).includes(K.TARGET[enemy])?12000:0);
let node=plan.n,score=0;if(plan.type==='move'||plan.type==='deploy'){score+=120-dist(node,K.TARGET[owner])*18;score-=surroundRisk(plan.p,node);for(const e of K.s[enemy].field)if(e.pos&&K.neigh(node).includes(e.pos))score+=K.battleScore(plan.p,e)*0.8;for(const e of K.s[enemy].field)if(K.canAct(e)&&K.moveTargets(e,enemy).includes(K.TARGET[enemy]))score-=9000;}
return score;}
K.chooseAiPlan=function(){const win=genPlans('p2').find(p=>(p.type==='move'||p.type==='deploy')&&p.n===K.TARGET.p2);if(win)return{...win,score:999999};const def=defensivePlan('p2');if(def)return def;let best=null;for(const p of genPlans('p2')){const sc=planScore(p,'p2');if(!best||sc>best.score)best={...p,score:sc};}return best;};
K.runAi=function(){const s=K.s;if(!s.ai||s.turn!=='p2'||s.win||s.locked||s.phase!=='idle')return;const plan=K.chooseAiPlan();if(!plan){K.log('AIは動けません。');K.endTurn();return;}if(plan.type==='wake'){plan.p.status.condition=null;K.log('AIは'+plan.p.n+'を起こしました。');K.endTurn();return;}if(plan.type==='deploy'){K.log('AI: '+plan.p.n+'を出撃。評価 '+Math.round(plan.score));K.deploy(plan.p,plan.n);return;}if(plan.type==='move'){K.log('AI: '+plan.p.n+'が移動。評価 '+Math.round(plan.score));K.movePiece(plan.p,plan.n);return;}if(plan.type==='battle'){K.s.pendingAttacker=plan.p.id;K.log('AI: '+plan.p.n+'で'+plan.d.n+'にバトル。評価 '+Math.round(plan.score));K.startBattle(plan.d.id);}}
K.aiChooseEnemy=function(){const a=K.byId(K.s.pendingAttacker);if(!a||K.s.turn!=='p2'||K.s.phase!=='chooseBattle')return;let best=null;for(const e of K.battleableEnemies(a)){const sc=K.battleScore(a,e);if(!best||sc>best.sc)best={e,sc};}if(best&&best.sc>-50){K.log('AIは'+best.e.n+'にバトルします。');K.startBattle(best.e.id);}else{K.log('AIはバトルしないを選びました。');K.endTurn();}}
K.scheduleAi=function(){clearTimeout(K.aiTimer);if(K.s&&K.s.ai&&K.s.turn==='p2'&&!K.s.win&&!K.s.locked&&K.s.phase==='idle')K.aiTimer=setTimeout(K.runAi,600);};
})(window.KOMA);
