window.KOMA=window.KOMA||{};
(function(K){
K.ability=function(p,key){const a=K.FIGURES[p.fig].ability;return !!(a&&a[key]);};
K.canAct=p=>p.wait<=0&&p.status.condition!=='sleep'&&p.status.condition!=='frozen';
K.isPassThrough=p=>p.status.condition==='sleep'||p.status.condition==='frozen';
K.futureMp=p=>Math.max(0,p.mp-(p.status.mpMinus||0));
K.effectiveMp=function(p,owner=K.s.turn){if(!K.canAct(p))return 0;return Math.max(0,K.futureMp(p)-(K.s.turnCount===1&&owner==='p1'?1:0));};
K.occupiedAll=function(){return new Set(K.all().map(p=>p.pos));};
K.blockedFor=function(self){if(K.ability(self,'passThrough'))return new Set();return new Set(K.all().filter(p=>p!==self&&!K.isPassThrough(p)).map(p=>p.pos));};
K.reachableFrom=function(start,mp,blocked,self){const vis=new Map([[start,0]]),q=[start];while(q.length){const c=q.shift(),d=vis.get(c);if(d>=mp)continue;for(const n of K.neigh(c)){if(!blocked.has(n)&&!vis.has(n)){vis.set(n,d+1);q.push(n);}if(self&&K.ability(self,'jump')&&d+2<=mp&&K.at(n)){for(const land of K.neigh(n)){if(land===c||blocked.has(land)||K.at(land)||vis.has(land))continue;vis.set(land,d+2);q.push(land);}}}}vis.delete(start);return[...vis.keys()];};
K.findPath=function(start,end,mp,blocked,self){const seen=new Map([[start,0]]),prev=new Map(),q=[start];while(q.length){const c=q.shift(),d=seen.get(c);if(c===end)break;if(d>=mp)continue;for(const n of K.neigh(c)){if(!blocked.has(n)&&!seen.has(n)){seen.set(n,d+1);prev.set(n,c);q.push(n);}if(self&&K.ability(self,'jump')&&d+2<=mp&&K.at(n)){for(const land of K.neigh(n)){if(land===c||blocked.has(land)||K.at(land)||seen.has(land))continue;seen.set(land,d+2);prev.set(land,c);q.push(land);}}}}
if(!seen.has(end))return[start,end];const path=[end];let cur=end;while(cur!==start){cur=prev.get(cur);if(!cur)return[start,end];path.unshift(cur);}return path;};
K.moveTargets=function(p,owner=p.owner){const stops=K.occupiedAll();stops.delete(p.pos);return K.reachableFrom(p.pos,K.effectiveMp(p,owner),K.blockedFor(p),p).filter(n=>!stops.has(n));};
K.entryTargets=function(p,owner){const total=Math.max(0,p.mp-(K.s.turnCount===1&&owner==='p1'?1:0));if(total<=0||p.wait>0)return[];const r=new Set(),stops=K.occupiedAll(),blocked=K.ability(p,'passThrough')?new Set():new Set(K.all().filter(x=>!K.isPassThrough(x)).map(x=>x.pos));for(const sp of K.SPAWN[owner]){if(K.at(sp))continue;r.add(sp);for(const n of K.reachableFrom(sp,total-1,blocked,p))if(!stops.has(n))r.add(n);}return[...r];};
K.adjacentEnemies=p=>K.all().filter(o=>o.owner!==p.owner&&p.pos&&K.neigh(p.pos).includes(o.pos));
K.battleableEnemies=p=>K.adjacentEnemies(p).filter(e=>e.status.condition!=='sleep'&&e.status.condition!=='frozen');
K.canWakeByAlly=function(p){return(p.status.condition==='sleep'||p.status.condition==='frozen')&&K.s[p.owner].field.some(a=>a!==p&&K.canAct(a)&&K.neigh(a.pos).includes(p.pos));};
K.tryWake=function(p){if(p.owner===K.s.turn&&K.canWakeByAlly(p)){const old=p.status.condition;p.status.condition=null;K.log(p.n+'は味方にタッチされて'+(old==='frozen'?'こおり':'ねむり')+'が治りました。');K.endTurn();return true;}return false;};
K.endTurn=function(){const prev=K.s.turn;K.s.pendingBattle=null;K.clearSelection();K.tickWait(prev);K.s.turn=K.other(prev);K.s.turnCount++;K.checkNoMoveWin();K.render&&K.render();};
K.addWait=function(p,n=1){p.wait=Math.max(p.wait,p.owner===K.s.turn?n+1:n);};
K.addBenchWait=function(p,n=1){p.wait=Math.max(p.wait,n);};
K.removeField=function(p){K.s[p.owner].field=K.s[p.owner].field.filter(x=>x.id!==p.id);p.pos=null;};
K.resetOnBench=function(p){p.status=K.freshStatus();p.focusGuard=false;};
K.fxPiece=function(p,cls,done){if(!p){done&&done();return;}K.s.fx=K.s.fx||{};K.s.fx[p.id]={cls};K.render&&K.render();window.setTimeout(()=>{if(K.s.fx)delete K.s.fx[p.id];done&&done();},360);};
K.sendToBench=function(p,done){K.fxPiece(p,'fx-bench',()=>{K.removeField(p);K.resetOnBench(p);K.addBenchWait(p);K.s[p.owner].bench.push(p);K.log(p.n+'はベンチへ戻されました。');K.render&&K.render();done&&done();});};
K.pc=function(p){K.removeField(p);K.resetOnBench(p);const pl=K.s[p.owner];if(pl.pc.length>=2){const out=pl.pc.shift();K.resetOnBench(out);K.addBenchWait(out);pl.bench.push(out);K.log(out.n+'がPCから待機1でベンチへ戻りました。');}pl.pc.push(p);K.log(p.n+'はPCへ送られました。');};
K.resolveSurrounds=function(){let changed=true;while(changed){changed=false;for(const p of[...K.all()]){const ns=K.neigh(p.pos);if(ns.length&&ns.every(n=>{const o=K.at(n);return o&&o.owner!==p.owner;})){K.log(p.n+'は包囲されました。');K.pc(p);changed=true;break;}}}};
K.checkNoMoveWin=function(){if(K.s.win)return;const owner=K.s.turn;const can=K.s[owner].bench.some(p=>K.entryTargets(p,owner).length)||K.s[owner].field.some(p=>K.canWakeByAlly(p)||(K.canAct(p)&&(K.moveTargets(p,owner).length||K.battleableEnemies(p).length)));if(!can){K.s.win=K.other(owner);K.log(owner+'は動けません。'+K.s.win+'の勝利です。');}};
K.animateMovePath=function(p,path,done){if(!path||path.length<2){done();return;}const s=K.s;s.locked=true;s.phase='moving';s.targets=[];s.attacks=[];s.selectedId=null;s.selectedType=null;s.pendingAttacker=null;let i=1;function step(){if(i>=path.length){done();return;}const next=path[i++];const occ=K.at(next);if(!occ||occ===p){p.pos=next;K.setFx(p,path[Math.max(0,i-2)],next);K.render&&K.render();window.setTimeout(step,260);}else{window.setTimeout(step,120);}}K.render&&K.render();window.setTimeout(step,120);};
K.placePiece=function(p,node,from){p.pos=node;K.setFx(p,from,node);if(node===K.TARGET[p.owner]){K.s.win=p.owner;K.clearSelection();K.s.locked=false;K.log(p.n+'がゴールしました。'+p.owner+'の勝利！');K.render&&K.render();return;}K.resolveSurrounds();if(!K.s[p.owner].field.includes(p)){K.s.locked=false;K.endTurn();return;}const enemies=K.battleableEnemies(p);if(enemies.length){K.s.locked=false;K.s.phase='chooseBattle';K.s.pendingAttacker=p.id;K.s.selectedId=null;K.s.selectedType=null;K.s.targets=[];K.s.attacks=enemies.map(e=>e.pos);K.log('隣接敵を選ぶとバトルします。戦わない場合は「バトルしない」。');K.render&&K.render();if(p.owner==='p2'&&K.s.ai)window.setTimeout(()=>K.aiChooseEnemy(),350);return;}K.s.locked=false;K.endTurn();};
K.deploy=function(p,node){const pl=K.s[p.owner];pl.bench=pl.bench.filter(x=>x.id!==p.id);pl.field.push(p);K.log(p.n+'が出撃しました。');K.placePiece(p,node,null);};
K.movePiece=function(p,node){const old=p.pos,mp=K.effectiveMp(p,p.owner),path=K.findPath(old,node,mp,K.blockedFor(p),p);K.log(p.n+'が '+old+' → '+node+' に移動します。');K.animateMovePath(p,path,()=>{K.log(p.n+'が '+old+' → '+node+' に移動しました。');K.placePiece(p,node,old);});};
K.cloneSeg=x=>({c:x.c,n:x.n,d:x.d,s:x.s,e:x.e?{...x.e}:null,boost:x.boost||1});
K.wheelFor=function(p,silent=false){let w=K.FIGURES[p.fig].w.map(K.cloneSeg),total=0;const tune=p.tuning||{};w=w.map((seg,i)=>{const z=K.cloneSeg(seg);z.s=Math.max(1,z.s+(tune[i]||0));total+=z.s;return z;});const diff=100-total;if(w.length)w[w.length-1].s=Math.max(1,w[w.length-1].s+diff);if(p.status.condition==='paralyze'){const valid=w.filter(x=>x.c!=='miss'),min=Math.min(...valid.map(x=>x.s));for(const seg of w)if(seg.c!=='miss'&&seg.s===min){seg.c='miss';seg.n='ミス';seg.d=0;seg.e=null;seg.paralyzed=true;}if(!silent)K.log(p.n+'はマヒで最小幅の技がミス扱いです。');}if(p.status.condition==='frozen'){for(const seg of w){seg.c='miss';seg.n='ミス';seg.d=0;seg.e=null;}if(!silent)K.log(p.n+'はこおりで全技がミス扱いです。');}return w;};
K.baseValue=function(seg,p){let v=seg.d||0;if(seg.boost)v*=seg.boost;if((seg.c==='white'||seg.c==='gold')&&p.status.condition==='poison')v=Math.max(0,v-20);if((seg.c==='white'||seg.c==='gold')&&p.status.condition==='toxic')v=Math.max(0,v-40);if((seg.c==='white'||seg.c==='gold')&&p.status.condition==='burn')v=Math.max(0,v-10);return v;};
K.spin=function(p){const w=K.wheelFor(p),total=w.reduce((a,b)=>a+b.s,0);let r=Math.random()*total,acc=0;for(let i=0;i<w.length;i++){const seg=w[i],st=acc/total*360;acc+=seg.s;const en=acc/total*360;if((r-=seg.s)<=0){let out={seg:K.cloneSeg(seg),center:(st+en)/2,index:i,wheel:w,chain:[]};if(p.status.condition==='confuse'&&w.length>1){const old=out.seg.n,ni=(i+1)%w.length;out.seg=K.cloneSeg(w[ni]);out.index=ni;out.chain=[old,'こんらん'];K.log(p.n+'は混乱で技がずれました。');}return out;}}return{seg:K.cloneSeg(w[w.length-1]),center:350,index:w.length-1,wheel:w,chain:[]};};
K.resolveSpin=function(p){const r=K.spin(p);if(r.seg.e&&r.seg.e.focus){p.focusGuard=true;const next=K.spin(p);next.chain=[r.seg.n];if(next.seg.c==='white'||next.seg.c==='gold')next.seg.boost=r.seg.e.boost||2;else next.seg.noKo=true;return next;}return r;};
K.compare=function(a,b,ap,bp){const A=a.c,B=b.c,av=K.baseValue(a,ap),bv=K.baseValue(b,bp);if(A==='blue'||B==='blue')return{winner:'draw',ko:false,blue:true,mode:A==='blue'&&B==='blue'?'blue-both':'blue-null'};if(A==='miss'&&B==='miss')return{winner:'draw',ko:false,mode:'null'};if(A==='miss')return{winner:'def',ko:(B==='white'||B==='gold')&&bv>0,mode:'oneway'};if(B==='miss')return{winner:'atk',ko:(A==='white'||A==='gold')&&av>0,mode:'oneway'};if(A==='gold'&&B==='purple')return{winner:'atk',ko:av>0,mode:'oneway'};if(B==='gold'&&A==='purple')return{winner:'def',ko:bv>0,mode:'oneway'};if(A==='purple'||B==='purple'){if(A==='purple'&&B==='purple'){if(av===bv)return{winner:'draw',ko:false,mode:'null'};return{winner:av>bv?'atk':'def',ko:false,mode:'oneway'};}return{winner:A==='purple'?'atk':'def',ko:false,mode:'oneway'};}if(av===bv)return{winner:'draw',ko:false,mode:'damage-draw'};const win=av>bv?'atk':'def';return{winner:win,ko:K.baseValue(win==='atk'?a:b,win==='atk'?ap:bp)>0,mode:'damage'};};
K.applyEffect=function(seg,user,target,done){const e=seg.e;if(!e){done&&done();return;}if(e.selfWait)K.addWait(user,e.selfWait);if(e.fly||e.selfBench){K.fxPiece(user,'fx-fly',()=>{K.sendToBench(user,done);});return;}if(e.condition&&target){target.status.condition=e.condition;K.log(target.n+'は'+K.COND[e.condition]+'になりました。');}if(e.wait&&target){K.addWait(target,e.wait);K.log(target.n+'にウェイトがつきました。');}if(e.mpMinus&&target){target.status.mpMinus=Math.max(target.status.mpMinus,e.mpMinus);K.log(target.n+'にMP-'+e.mpMinus+'がつきました。');}if(e.swap&&target&&user.pos&&target.pos){K.fxPiece(user,'fx-swap');K.fxPiece(target,'fx-swap',()=>{const a=user.pos;user.pos=target.pos;target.pos=a;K.log(user.n+'と'+target.n+'が入れ替わりました。');K.render&&K.render();done&&done();});return;}if(e.bench&&target&&K.s[target.owner].field.includes(target)){K.sendToBench(target,done);return;}if(e.selfko&&target){K.pc(user);if(K.s[target.owner].field.includes(target))K.pc(target);}done&&done();};
K.resolveBattle=function(a,d,as,ds,out){K.log(a.n+': '+K.segText(as.seg,a)+' / '+d.n+': '+K.segText(ds.seg,d));function finish(){a.focusGuard=false;d.focusGuard=false;K.s.pendingBattle=null;K.s.locked=false;K.resolveSurrounds();K.endTurn();}
if(out.blue){if(out.mode!=='blue-both'){const bp=as.seg.c==='blue'?a:d,bs=as.seg.c==='blue'?as.seg:ds.seg;K.applyEffect(bs,bp,null,finish);return;}K.log('青技同士で打ち消し。');finish();return;}
if(out.winner==='draw'){K.log('無効試合。');if(out.mode==='damage-draw'){K.applyEffect(as.seg,a,d,()=>K.applyEffect(ds.seg,d,a,finish));return;}finish();return;}
const atkWin=out.winner==='atk',winP=atkWin?a:d,loseP=atkWin?d:a,winSeg=atkWin?as.seg:ds.seg,loseSeg=atkWin?ds.seg:as.seg;K.applyEffect(winSeg,winP,loseP,()=>{if(out.mode==='damage'&&(loseSeg.c==='white'||loseSeg.c==='gold'))K.applyEffect(loseSeg,loseP,winP,afterLoseEffect);else afterLoseEffect();});
function afterLoseEffect(){if(out.ko&&K.s[loseP.owner].field.includes(loseP)){if(loseP.focusGuard||loseSeg.noKo){K.log(loseP.n+'は気絶しません。');finish();}else if(!(winSeg.e&&(winSeg.e.bench||winSeg.e.selfko||winSeg.e.fly||winSeg.e.selfBench)))K.fxPiece(loseP,'fx-bench',()=>{K.pc(loseP);finish();});else finish();}else{K.log(winP.n+'の判定勝ち。');finish();}}
};
K.startBattle=function(defenderId){const a=K.byId(K.s.pendingAttacker||K.s.selectedId),d=K.byId(defenderId);if(!a||!d||!K.neigh(a.pos).includes(d.pos)){K.log('隣接していないのでバトルできません。');K.render&&K.render();return;}if(a.status.condition==='sleep'||a.status.condition==='frozen'||d.status.condition==='sleep'||d.status.condition==='frozen'){K.log('ねむり/こおり状態ではバトルできません。');K.render&&K.render();return;}K.s.locked=true;K.s.phase='battle';K.s.pendingBattle={a:a.id,d:d.id};K.s.selectedId=null;K.s.selectedType=null;K.s.targets=[];K.s.attacks=[];K.s.pendingAttacker=null;const as=K.resolveSpin(a),ds=K.resolveSpin(d),out=K.compare(as.seg,ds.seg,a,d);K.showBattle(a,d,as,ds,out,()=>K.resolveBattle(a,d,as,ds,out));};
})(window.KOMA);
