window.KOMA=window.KOMA||{};
(function(K){
const $=q=>document.querySelector(q);
K.colorOf=c=>({miss:'#ef4444',white:'#f8fafc',gold:'#facc15',purple:'#a855f7',blue:'#38bdf8'}[c]||'#fff');
K.segText=function(seg,p){if(seg.c==='miss')return seg.n;if(seg.c==='blue')return seg.n+' [青]';if(seg.c==='purple')return seg.n+' [紫 ★'+seg.d+']';if(seg.c==='gold')return seg.n+' [金 '+K.baseValue(seg,p)+']';return seg.n+' [白 '+K.baseValue(seg,p)+']';};
function moveLabel(seg,p){if(seg.c==='miss')return'ミス';if(seg.c==='blue')return seg.n+' 青';if(seg.c==='purple')return seg.n+' ★'+seg.d;if(seg.c==='gold')return seg.n+' 金'+K.baseValue(seg,p);return seg.n+' '+K.baseValue(seg,p);}
function wheelBg(w){let total=w.reduce((a,b)=>a+b.s,0),acc=0,parts=[],sep=.9;for(const seg of w){const st=acc/total*360;acc+=seg.s;const en=acc/total*360,a=Math.min(st+sep,en),b=Math.max(a,en-sep);parts.push('#111827 '+st+'deg '+a+'deg');parts.push(K.colorOf(seg.c)+' '+a+'deg '+b+'deg');parts.push('#111827 '+b+'deg '+en+'deg');}return'conic-gradient('+parts.join(',')+')';}
function wheelHtml(w,p){let total=w.reduce((a,b)=>a+b.s,0),acc=0,out='';for(const seg of w){const st=acc/total*360;acc+=seg.s;const c=(st+acc/total*360)/2;out+='<span class="wlabel" style="transform:rotate('+c+'deg) translateY(-58px) rotate('+(-c)+'deg)">'+moveLabel(seg,p)+'</span>';}return out;}
function effText(e){if(!e)return'追加効果なし';let a=[];if(e.focus)a.push('再スピン/気絶回避/強化');if(e.condition)a.push(K.COND[e.condition]+'付与');if(e.wait)a.push('相手ウェイト');if(e.selfWait)a.push('自分ウェイト');if(e.mpMinus)a.push('MP-'+e.mpMinus);if(e.bench)a.push('ベンチへ戻す');if(e.swap)a.push('入れ替え');if(e.selfko)a.push('両方PC');if(e.chain)a.push('連続スピン(仮)');return a.join('・');}
function segList(w,p){return w.map(seg=>'<div class="seg"><span class="sw" style="background:'+K.colorOf(seg.c)+'"></span><span>'+K.segText(K.cloneSeg(seg),p)+' / 幅'+seg.s+(seg.paralyzed?' / マヒでミス化':'')+(seg.e?' / '+effText(seg.e):'')+'</span></div>').join('');}
function marks(p){let m='';if(p.wait>0)m+='待';if(p.status.condition==='paralyze')m+='麻';if(p.status.condition==='poison')m+='毒';if(p.status.condition==='toxic')m+='猛';if(p.status.condition==='sleep')m+='眠';if(p.status.condition==='frozen')m+='氷';if(p.status.condition==='burn')m+='火';if(p.status.condition==='confuse')m+='混';if(p.status.mpMinus)m+='M-';return m;}
function bindLong(el,p){let t=null;const open=e=>{e.preventDefault();e.stopPropagation();showInfo(p);};el.oncontextmenu=open;el.addEventListener('pointerdown',e=>{t=setTimeout(()=>open(e),560);});['pointerup','pointercancel','pointerleave','pointermove'].forEach(ev=>el.addEventListener(ev,()=>{clearTimeout(t);}));}
function abilityHtml(p){const a=K.FIGURES[p.fig].ability;if(!a)return'<p><b>特性:</b> なし</p>';return'<p><b>特性:</b> '+a.name+'<br>'+a.text+'</p>';}
function showInfo(p){const f=K.FIGURES[p.fig];$('#infoTitle').textContent=p.n+' の情報';$('#infoBody').innerHTML='<p><b>所有:</b> '+p.owner+' / <b>MP:</b> '+p.mp+' / <b>レア:</b> '+f.r+' / <b>Lv:</b> '+(p.level||1)+'</p><p><b>位置:</b> '+(p.pos||'ベンチ')+' / <b>状態:</b> '+(marks(p)||'なし')+'</p>'+abilityHtml(p)+'<h3>技</h3>'+segList(K.wheelFor(p),p)+'<h3>状態メモ</h3><p>どく:-20 / どくどく:-40 / マヒ:最小幅技がミス / 混乱:隣の技へずれる / 眠り:行動不能・通過可・味方タッチ回復・バトル不可 / 氷:行動不能・通過可・全技ミス</p><p>Lv強化用の tuning データ対応済み。</p>';$('#infoOverlay').style.display='flex';}
K.render=function(){const s=K.s;if(!s)return;document.body.classList.toggle('locked',s.locked);$('#turnCount').textContent=s.turnCount;renderStatus();renderBoard();renderBench('p2','#topBench');renderBench('p1','#bottomBench');renderPc();renderActions();$('#log').textContent=s.log.slice(0,22).join('\n');K.scheduleAi&&K.scheduleAi();};
function renderStatus(){const s=K.s,sel=K.byId(s.selectedId);$('#status').textContent=s.win?s.win+' の勝利です！':s.locked?'バトル中...':s.phase==='chooseBattle'?'隣接敵を選択中 / バトルしないも選べます':s.turn==='p2'?'AI思考中...':sel?'自分のターン / 選択中: '+sel.n+'（同じ駒かボタンで解除）':'自分のターン / 駒を選択';}
function renderActions(){const b=$('#skipAction');if(K.s.phase==='chooseBattle'&&K.s.turn==='p1'){b.disabled=false;b.textContent='バトルしない';}else if(K.s.phase==='chooseTarget'&&K.s.turn==='p1'){b.disabled=false;b.textContent='選択解除';}else{b.disabled=true;b.textContent='バトルしない';}$('#aiBtn').textContent=K.s.ai?'AI ON':'AI OFF';}
function renderBoard(){const s=K.s,b=$('#board');b.innerHTML='';const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('class','lines');svg.setAttribute('viewBox','0 0 100 100');svg.setAttribute('preserveAspectRatio','none');for(const [a,c]of K.EDGES){const line=document.createElementNS('http://www.w3.org/2000/svg','line');line.setAttribute('class','edge');line.setAttribute('x1',K.NODES[a][0]);line.setAttribute('y1',K.NODES[a][1]);line.setAttribute('x2',K.NODES[c][0]);line.setAttribute('y2',K.NODES[c][1]);svg.appendChild(line);}if(s.fx&&K.NODES[s.fx.from]&&K.NODES[s.fx.to]){const [x1,y1]=K.NODES[s.fx.from],[x2,y2]=K.NODES[s.fx.to];const line=document.createElementNS('http://www.w3.org/2000/svg','line');line.setAttribute('class','moveFx');line.setAttribute('x1',x1);line.setAttribute('y1',y1);line.setAttribute('x2',x2);line.setAttribute('y2',y2);svg.appendChild(line);const dot=document.createElementNS('http://www.w3.org/2000/svg','circle');dot.setAttribute('class','moveDot');dot.setAttribute('cx',x2);dot.setAttribute('cy',y2);dot.setAttribute('r',3.2);svg.appendChild(dot);}b.append(svg);
for(const id of Object.keys(K.NODES)){const [x,y]=K.NODES[id],n=document.createElement('button');n.className='node';if(K.SPAWN.p1.includes(id)||K.SPAWN.p2.includes(id))n.classList.add('spawn');if(id===K.TARGET.p1||id===K.TARGET.p2){n.classList.add('goal');if(id===K.TARGET.p1)n.classList.add('player');}if(s.targets.includes(id))n.classList.add('reach');if(s.attacks.includes(id))n.classList.add('attack');n.style.left=x+'%';n.style.top=y+'%';n.textContent=id===K.TARGET.p1?'◀':id===K.TARGET.p2?'▶':(K.SPAWN.p1.includes(id)||K.SPAWN.p2.includes(id))?'◎':'';n.onclick=()=>clickNode(id);b.append(n);}for(const p of K.all()){const [x,y]=K.NODES[p.pos],el=document.createElement('div');el.className='fig '+p.owner+(s.selectedId===p.id?' sel':'')+(s.attacks.includes(p.pos)?' attackable':'')+(!K.canAct(p)?' waiting':'')+(s.lastMoved===p.id?' moved':'');el.style.left=x+'%';el.style.top=y+'%';el.innerHTML='<span>'+p.n+'</span><span class="mp">'+K.effectiveMp(p,p.owner)+'</span>'+(marks(p)?'<span class="mark">'+marks(p)+'</span>':'');el.onclick=()=>clickFigure(p);bindLong(el,p);b.append(el);}}
function renderBench(owner,sel){const row=$(sel);row.innerHTML='';for(const p of K.s[owner].bench){const slot=document.createElement('div');slot.className='slot';const btn=document.createElement('button');btn.className='benchBtn'+(K.s.selectedId===p.id?' active':'');btn.disabled=owner!==K.s.turn||owner!=='p1'||K.s.locked||K.s.phase==='chooseBattle'||p.wait>0||!!K.s.win;btn.textContent=p.n;btn.onclick=()=>selectBench(p);bindLong(btn,p);const meta=document.createElement('div');meta.className='meta';meta.textContent='MP '+p.mp+(p.wait?' / 待':'');slot.append(btn,meta);row.append(slot);}}
function renderPc(){for(const id of['p1','p2']){const box=$('#'+id+'pc');box.innerHTML='';for(const p of K.s[id].pc){const c=document.createElement('span');c.textContent=p.n;box.append(c);}}}
function cancelSelection(msg='選択を解除しました。'){K.clearSelection();K.log(msg);K.render();}
function selectBench(p){if(K.s.phase==='chooseTarget'&&K.s.selectedId===p.id)return cancelSelection();const targets=K.entryTargets(p,'p1');if(!targets.length){K.log(p.n+'は出撃できません。');K.render();return;}K.s.phase='chooseTarget';K.s.selectedType='bench';K.s.selectedId=p.id;K.s.targets=targets;K.s.attacks=[];K.log(p.n+'を選択。出撃先を選んでください。');K.render();}
function selectField(p){if(K.s.phase==='chooseTarget'&&K.s.selectedId===p.id)return cancelSelection();if(K.tryWake(p))return;if(!K.canAct(p)){K.log(p.n+'は行動不能です。');K.render();return;}K.s.phase='chooseTarget';K.s.selectedType='field';K.s.selectedId=p.id;K.s.targets=K.moveTargets(p,'p1');K.s.attacks=K.battleableEnemies(p).map(e=>e.pos);K.log(p.n+'を選択。移動先か隣接敵を選んでください。');K.render();}
function clickNode(node){const s=K.s;if(s.locked||s.win)return;const occ=K.at(node);if(s.phase==='chooseBattle'){if(occ&&canChooseEnemy(occ))K.startBattle(occ.id);return;}if(occ&&occ.owner==='p1'&&s.turn==='p1'&&(s.phase==='idle'||s.phase==='chooseTarget')){selectField(occ);return;}if(s.phase!=='chooseTarget')return;if(occ&&occ.owner!==s.turn&&canChooseEnemy(occ)){K.startBattle(occ.id);return;}if(!s.targets.includes(node)||occ)return;const p=K.byId(s.selectedId);if(!p)return;if(s.selectedType==='bench')K.deploy(p,node);else K.movePiece(p,node);}
function clickFigure(p){const s=K.s;if(s.locked||s.win)return;if(s.phase==='chooseBattle'){if(canChooseEnemy(p))K.startBattle(p.id);else K.log('隣接している敵を選んでください。');K.render();return;}if(p.owner==='p1'&&s.turn==='p1'&&(s.phase==='idle'||s.phase==='chooseTarget')){selectField(p);return;}if(s.phase==='chooseTarget'&&p.owner!==s.turn&&canChooseEnemy(p)){K.startBattle(p.id);return;}K.log('今はその駒を選べません。');K.render();}
function canChooseEnemy(p){const a=K.byId(K.s.pendingAttacker||K.s.selectedId);return a&&p&&p.owner!==a.owner&&p.status.condition!=='sleep'&&K.neigh(a.pos).includes(p.pos);}
K.showBattle=function(a,d,as,ds,out,apply){const topP=a.owner==='p2'?a:d,botP=a.owner==='p1'?a:d,topR=topP===a?as:ds,botR=botP===a?as:ds,tw=$('#topWheel'),bw=$('#bottomWheel'),btn=$('#continueBattle');$('#topName').textContent='相手: '+topP.n;$('#bottomName').textContent='自分: '+botP.n;$('#topResult').textContent='';$('#bottomResult').textContent='';$('#topSegs').innerHTML=segList(topR.wheel,topP);$('#bottomSegs').innerHTML=segList(botR.wheel,botP);$('#battleResult').textContent=(a.owner==='p2'?'相手の':'自分の')+a.n+'がバトル。ルーレット回転中...';btn.style.display='none';for(const w of[tw,bw]){w.style.transition='none';w.style.transform='rotate(0deg)';}tw.style.background=wheelBg(topR.wheel);bw.style.background=wheelBg(botR.wheel);tw.innerHTML=wheelHtml(topR.wheel,topP);bw.innerHTML=wheelHtml(botR.wheel,botP);$('#battleOverlay').style.display='flex';K.render();setTimeout(()=>{tw.style.transition='transform 1.45s cubic-bezier(.12,.8,.18,1)';bw.style.transition='transform 1.45s cubic-bezier(.12,.8,.18,1)';tw.style.transform='rotate('+(1440+360-topR.center)+'deg)';bw.style.transform='rotate('+(1440+360-botR.center)+'deg)';},50);setTimeout(()=>{$('#topResult').textContent=(topR.chain&&topR.chain.length?topR.chain.join('→')+'→':'')+K.segText(topR.seg,topP);$('#bottomResult').textContent=(botR.chain&&botR.chain.length?botR.chain.join('→')+'→':'')+K.segText(botR.seg,botP);$('#battleResult').textContent=out.blue?'青技で完全無効':out.winner==='draw'?'無効試合':out.winner==='atk'?a.n+'の判定勝ち':d.n+'の判定勝ち';btn.style.display='block';btn.onclick=()=>{$('#battleOverlay').style.display='none';apply();};},1650);};
K.bindUi=function(){$('#resetBtn').onclick=()=>{K.start();};$('#skipAction').onclick=()=>{if(K.s.phase==='chooseBattle'&&K.s.turn==='p1'){K.log('バトルしないを選びました。');K.endTurn();}else if(K.s.phase==='chooseTarget'&&K.s.turn==='p1'){cancelSelection();}};$('#aiBtn').onclick=()=>{K.s.ai=!K.s.ai;K.log(K.s.ai?'AIをONにしました。':'AIをOFFにしました。');K.render();};$('#infoClose').onclick=()=>{$('#infoOverlay').style.display='none';};};
})(window.KOMA);
